spring:
  data:
    mongodb:
      auto-index-creation: true

jwt:
  access-token-expiration-ms: 60000     # 1 min in tests
  refresh-token-expiration-ms: 120000   # 2 min in tests

google:
  client-id: test-client-id
  client-secret: test-client-secret
  redirect-uri: http://localhost:8080/auth/callback
